# -*- coding: utf-8 -*-
import json
import random
import re

import webapp2

import alertlib

_DEFAULT_CHANNEL = "#1s-and-0s"

_RESPOND_REGEXP = re.compile(r'culture us$')

_CULTURE_MESSAGES = [
    # Adding a message?  See https://api.slack.com/docs/formatting for
    # formatting instructions.
    "<https://sites.google.com/a/khanacademy.org/forge/for-developers|Shipping beats perfection>.",
    "Iterate on ideas before diving into code. <http://www.designstaff.org/articles/product-design-sprint-day-2-diverge-2012-10-26.html|Design sprints> are being organized by Jason and others and work well for both huge projects and small features.",
    "Concerned about the hacks in our code? Upset that the product's not good enough? Have no fear, we're getting better fast. Our site used to <https://s3.amazonaws.com/KA-share/old.png|look like this> and it was generated by one big main.py file.",
    "<https://sites.google.com/a/khanacademy.org/forge/for-khan-employees/-new-employees-onboard-doc/general-setup/welcome-to-ka|Our core company values.>",
    "Have anything to demo at the next Monday all-hands? Everything that's shipped to real users is eligible. Show off.",
    "<https://sites.google.com/a/khanacademy.org/forge/for-developers|Be open, share your work>.",
    "It's ok to leave (or simply not attend) any meeting that you don't feel is important for you.",
    "<https://sites.google.com/a/khanacademy.org/forge/for-khan-employees/email-transparency|Email transparency> makes it easy for anybody to follow the goings on of teams they're interested in. <https://groups.google.com/a/khanacademy.org/forum/#!forumsearch/(email-transparency)|Join any list>.",
    "As a cow, I am fairly proud of having written our <https://docs.google.com/a/khanacademy.org/document/d/1P6fweXJpYFAaE8nXrAVA9mt8qx7vHlUDo-OMtxmViAQ/edit|Career Development doc>. Hard to do w/ just hooves.",
    "Keep learning — <https://sites.google.com/a/khanacademy.org/forge/for-khan-employees/conferences|we'll send you to conferences to do so>.",
    "Anybody can fix anything. (And anybody can run a <https://gist.github.com/spicyj/8df622f1d18b4cc8f71b|FIXIT> for themselves or their team.)",
    "Wading into some old code that's really disgusting compared to your brilliant new feature? You don't have to fix everything all at once. \"Leave it better\" and use # TODOs liberally. (Ben says he's sorry for the old code.)",
    "Wanna teach the team about anything? Spread good habits? Show off what you're building? <http://khanacademy.org/r/speaknow|Sign up to Speak Now> in the future after Wednesday's dev sitdown!",
    "Will just leave these <https://www.khanacademy.org/stories|users stories here>.",
    "Do you need anything to do your job well? Hardware? Software? Food? Coach K bobblehead for your desk? <https://sites.google.com/a/khanacademy.org/forge/for-khan-employees/how-to-buy-software-hardware-anything-you-need-to-get-your-job-done-well|It's easy to get whatever you need>, and if you have any trouble ping Kamens quickly.",
    "Shipping anything sizable? <http://www.joelonsoftware.com/articles/fog0000000012.html|Dog food> it! Schedule a dogfooding hour, ping in hipchat to gather friendly eaters of dog food, profit.",
    "<https://www.khanacademy.org/r/wtf|Why are we building what we're building? What are we building? Who is doing what?>",
    "<https://sites.google.com/a/khanacademy.org/forge/for-developers/performance|Performance is a feature> and is everyone's job. Unsure how to profile your code? No worries, just ask, we have some perf nuts on the team.",
    "Anybody can <https://sites.google.com/a/khanacademy.org/forge/for-developers/deployment-guidelines|own a deploy>. If you've got big changes going out, you're probably that anybody. I (Culture Cow), may one day even keep track of a deploy count leaderboard and spit it out here!",
    "<http://arguingwithalgorithms.blogspot.com/2013/03/coding-for-review.html|Write code with your reviewer in mind.>",
    "Recruiting is everyone's job. <http://missmarcialee.com/2013/04/on-building-a-better-product-team-letter-style/|Blogging about recruiting being everyone's job> is Marcia's job.",
    "<http://www.fraustollc.com/blog/shit_code/|\"Sure there's some bad code around, we've all seen it, hell we've all written it...If there is some smelly code out there, look for ways to make it better. Start by understanding the code, and then find ways to improve upon it.\">",
    "<http://bjk5.com/post/3994859683/code-reviews-as-relationship-builders-a-few-tips|Code reviews can make people happy.>",
    "@john created <http://ejohn.org/blog/gittip-at-khan-academy/|a way for all KA folks to give back to open source projects> that we lean on. <https://docs.google.com/a/khanacademy.org/spreadsheet/ccc?key=0ApubWHv0aMirdE9LODNJY0s4WXpXSlVYLVhrNmdocWc&usp=drive_web#gid=0|Setup your recurring donations>.",
    "Nobody needs permission to take an occasional brain break by working on a FIXIT task that's been bugging you or anything else valuable that's not on your main project's critical path.",
    "Record our most amusing conversations for posterity in the <https://docs.google.com/a/khanacademy.org/document/d/13bVo73p_qNTAFJKEXT-z6K_X8bAeOpzqXhopg9lDb-g/edit|Funny Quotes file>!",
    "Wanna run a usability test? DO EET. @jason's written a <https://docs.google.com/a/khanacademy.org/document/d/1HdnGR6V2vuwxlXswIPAZJ0_R0aXIXn5zhPXv9FTC8NY/edit|step-by-step guide to usability testing at KA>.",
    "DRI for a significant project? Make sure it's on the big whiteboard so you can share with the rest of the team during dev sitstand updown.",
    "Wondering what the heck people are talking about when they encourage you to plan your upcoming engineering milestones? Here're a <https://docs.google.com/a/khanacademy.org/document/d/10TDINtq27bCMRTLMOCeNydyCM8U_JKlGUcZFr62luIw/edit|few> <https://docs.google.com/a/khanacademy.org/document/d/1yra9IgIcagbZtQ2lO8_SmdUlfYgHX0OZCKAdqFaKYEg/edit#heading=h.gojm65fhaxoq|good> <https://docs.google.com/a/khanacademy.org/document/d/1PEwMhzqyzUteFtmJnbSUZd2oaZAJW8y-0ODp-BN-0i4/edit|examples> - and Ben's always available to talk about planning.",
    "<http://dashboards.khanacademy.org/is-ka-fast-yet|Is Khan Academy Fast Yet?>",
    "Are you stuck in <https://twitter.com/kamens/status/529443780273786881|google account limbo?!> Try adding `?authuser=1` to that drive url you tried to access with your personal gmail account"
]


def _get_culture():
    message = random.choice(_CULTURE_MESSAGES)
    moo = 'M' + 'o' * random.randrange(2, 10) + '.'
    return "%s  %s" % (message, moo)


class Culture(webapp2.RequestHandler):
    def get(self):
        """Invoked by cron."""
        alertlib.Alert(_get_culture()).send_to_slack(
            _DEFAULT_CHANNEL, sender="Culture Cow", icon_emoji=":cow:")

    def post(self):
        """Hit by the culture cow outgoing webhook in Slack.

        In this case, we can just return our reply in HTTP and be done.
        """
        if _RESPOND_REGEXP.search(self.request.get("text")) is not None:
            self.response.write(json.dumps({'text': _get_culture()}))


app = webapp2.WSGIApplication([
    ('/culture', Culture),
])
